### ISSUE TITLE
Allow [facebook] for example to be set to true without breaking the content of the button..

### ISSUE THREAD

**Issue by chrillewoodz** [MurhafSousli/ngx-sharebuttons#129]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

**Minimal usage of the plugin**

  @Input() buttons: any = {
    facebook: true,
    google: true,
    twitter: true,
    linkedIn: true,
    stumbleUpOn: true,
    reddit: false,
    tumblr: false,
    pinterest: false
  };

  <share-buttons
    [facebook]="buttons?.facebook"
    [google]="buttons?.google"
    [twitter]="buttons?.twitter"
    [linkedIn]="buttons?.linkedIn"
    [reddit]="buttons?.reddit"
    [tumblr]="buttons?.tumblr"
    [pinterest]="buttons?.pinterest"
    [stumbleUpOn]="buttons?.stumbleUpOn"
    [whatsApp]="buttons?.whatsApp"
  ></share-buttons>

This will display the buttons that have been provided but with the text "true" instead of their respective icons. Incredibly hard to customise which buttons you want when wrapping your component in another component.

**Comment by MurhafSousli** [comment]
Hi @chrillewoodz, if these inputs accept `true`, how would someone set his custom button template then?

**Comment by chrillewoodz** [comment]
In another input? Seems silly that you either have to provide the original template or false, not true and it sets the default template..

**Comment by chrillewoodz** [comment]
Or even better, via the `ng-template` tag. You don't provide template via input tags.

**Comment by MurhafSousli** [comment]
@chrillewoodz instead of giving instructions, I suggest you fork the plugin and create a PR, I would love to see your solution.

Just in case if you don't know, you can use:

 - single share button component e.g. `<share-button button="facebook"><share-button>`
 - share button directive e.g. `<button shareButton="twitter">Share on twitter</button>`

I think you will be able to accomplish what you want using one of them
