### ISSUE TITLE
Can't share anything

### ISSUE THREAD

**Issue by dshivrin** [MurhafSousli/ngx-sharebuttons#133]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search for a similar issue before submitting
[ ] feature request
[X ] question
```

**Minimal usage of the plugin**

Hi!
I'm relatively new to angular 2, and I'm trying to use this module.
I have followed the manual and It seems that I can't share, every site gives me an error.
For example Facebook says: 
"Sorry, something went wrong.
We're working on getting this fixed as soon as we can."

Google+ says that the link is illegal, etc
I have tried adding `<meta />` tags and still errors.

trying to share using only facebook api works without meta tags 
(https://developers.facebook.com/docs/plugins/share-button)

what am I missing?

My markUp
```html
<share-buttons [defaultStyle]="true" [showCount]="false"></share-buttons>
```
My app.module.ts
```ts
import { ShareButtonsModule } from 'ngx-sharebuttons';

@NgModule({
    imports: [
     ...
        ShareButtonsModule.forRoot()
    ],
```
My systemJS 
` 'ngx-sharebuttons':'node_modules/ngx-sharebuttons/bundles/ngx-sharebuttons.umd.js',`

there are no errors at all, It's just not working. 
what can I do?

**Comment by MurhafSousli** [comment]
It seems that you are trying to share from `localhost` environment, of course the social media network will not be able to access your local development app

**Comment by dshivrin** [comment]
You are currect sir. I have Deployed the app and it's working. Only whatsapp works in locallhost. 

I have another question:
I'm trying to use single share button but I keep getting "Cannot read property 'provider' of undefined".
or "Template parse errors:
Can't bind to 'description' since it isn't a known property of 'button'"
or just nothing happend, it shares the link only.

my code looks like this:

` <button class="btn btn-default whatsapp" shareButton="twitter" [sbDescription]="test description"><i class="fa fa-twitter"></i></button>`

or one of these:
<share-button class="facebook" [button]="fbButton" [description]="test" ></share-button>
<share-button class="facebook" [button]="fbButton" description="test" ></share-button>`

`import { ShareButton, ShareProvider } from 'ngx-sharebuttons';

 this.fbButton = new ShareButton(
            ShareProvider.FACEBOOK,
            '<i class="fa fa-facebook"></i>',
            'facebook',           
        );
`
Everything seems to error out. Is there something wrong that Am I doing something wrong?

**Comment by MurhafSousli** [comment]
For the share button directive, you have a problem with the input `[sbDescription]`.

When you use `[]` it means you are binding the input to a value (that can be changed dynamically), but  without `[]`, it means you are giving the input a static string value directly which is not dynamic.

So it depends, we use `shareButton` without `[]` because we do not have a plan to change it later, but for the description input, you might want to bind it to a variable `[sbDescription]="myDescValue"` or `[sbDescription]="'test description'"`.  otherwise use `sbDescription="test description"`. 

_**PLEASE NOT THE QUOTATIONS**_

in your case, this should work:
```html
<button class="btn btn-default whatsapp" shareButton="twitter" 
 [sbDescription]="'test description'"><i class="fa fa-twitter"></i></button>
```
***

For the single share button component, it is meant to be used internally in the library, but you can use it if you want, the code will be like this:
```ts
import { ShareButton, ShareProvider } from 'ngx-sharebuttons';

this.fbButton = new ShareButton(
     ShareProvider.FACEBOOK,
     '<i class="fa fa-twitter"></i>',
     'btn btn-default facebook'
);
```
template:
```html
 <share-button [button]="fbButton"
 [ngClass]="fbButton.classes" [description]="'test'"></share-button>
```

**Comment by dshivrin** [comment]
Great! thank you sir!
