### ISSUE TITLE
Link to Netlify App in Wiki More Prominently

### ISSUE THREAD

**Issue by ewwwgiddings** [MurhafSousli/ngx-sharebuttons#528]
#### I am submitting a

- [x] Question

#### Description

Is this up to date information? https://ngx-sharebuttons.netlify.app/#/share-buttons-component

If it is, can it be referenced more clearly in the Wiki. It is much easier to follow than the WIki docs.

#### What is the use-case or motivation for changing an existing behavior?

The WIki docs are helpful but I like using this link more. It's hard to remember how to get to it though because it's not prominently linked.

#### Which versions are you using for the following packages?

Angular:
ngx-sharebuttons:

**Comment by MurhafSousli** [comment]
The link you have is up to date, but I have to update it manually and sometime I could make a mistake or forget to update something, so the docs there are not automatically generated.

I prefer to use the wiki because it is easy to edit and always available, and you can simply add more wiki pages for a newer version and keep the old docs with almost no effort comparing to the work you will have to do in a demo app
