### ISSUE TITLE
LinkedIn button ignores description

### ISSUE THREAD

**Issue by mfenderov** [MurhafSousli/ngx-sharebuttons#662]
#### Reproduction

Steps to reproduce:
1. Add a LinkedIn button to the page
2. Add a description and URL to a LinkedIn button
3. Click it
4. Only the URL is added to the post

#### Expected Behavior

Description from a LinkedIn button is added to the post via `?text=` query attribute.

#### Actual Behavior

Only the URL is passed to the post.

#### Environment

- Angular: 17.3.4
- ngx-sharebuttons: 13.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment]
Yea, LinkedIn ignores description since 2020 as mentioned here https://stackoverflow.com/a/61856180/1015648

If you want the title and description to be displayed, the shared page must have OG meta tags as mentioned here https://www.linkedin.com/help/linkedin/answer/a521928/making-your-website-shareable-on-linkedin?lang=en
